# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='musician',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
