# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mus',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mus',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
